apiVersion: sourceplane.io/v1
kind: ComponentTree
metadata:
    intent: /Users/irinelinson/sourceplane/stack-tectonic-flare/intent.yaml
    generatedAt: "2026-05-16T05:39:35Z"
discovery:
    roots:
        - stacks
components:
    - name: stack-tectonic
      type: publish-stack
      domain: platform-stack
      enabled: false
      path: stacks/stack-tectonic-flare
      subscribe:
        environments:
            - name: dev
              profile: dry-run
            - name: staging
              profile: release
            - name: production
              profile: release
      inputs:
        name: stack-tectonic-flare
      labels:
        layer: platform
        provider: orun
      source: discovered
      sourcePath: stacks/stack-tectonic-flare/component.yaml
      fileSize: 395
      fileModTime: "2026-05-16T05:35:21.796977759Z"
