apiVersion: sourceplane.io/v1alpha1
kind: ExecutionProfile
metadata:
  name: terraform-verify
spec:
  description: Full non-mutating verification

  jobs:
    terraform:
      includeCapabilities:
        - terraform.setup
        - terraform.context
        - terraform.fmt
        - terraform.init
        - terraform.validate
        - terraform.plan
        - terraform.apply
