apiVersion: sourceplane.io/v1alpha1
kind: Composition
metadata:
  name: terraform
spec:
  type: terraform
  description: Terraform validation jobs for infra components

  schemaRef:
    name: terraform-component

  defaultJob: terraform
  defaultProfile: verify

  jobs:
    - name: terraform
      templateRef:
        name: terraform-validate

  profiles:
    - name: pull-request
      profileRef:
        name: terraform-pull-request
    - name: verify
      profileRef:
        name: terraform-verify
    - name: release
      profileRef:
        name: terraform-release
