apiVersion: sourceplane.io/v1alpha1
kind: ExecutionProfile
metadata:
  name: terraform-pull-request
spec:
  description: Fast PR validation with speculative planning

  jobs:
    terraform:
      includeCapabilities:
        - terraform.setup
        - terraform.context
        - terraform.fmt
        - terraform.init
        - terraform.validate
        - terraform.plan

      stepOverrides:
        terraform-init:
          run: terraform -chdir={{.terraformDir}} init -backend=false -input=false
        terraform-plan:
          run: terraform -chdir={{.terraformDir}} plan -no-color -lock=false
